# file: config.py

# === WIFI ===

SSID_AP = "MeinRoboter"
PASSWORD_AP = "Robo1234"

# === SERVO ===

CANNON_SERVO_PINS = [2, 3, 4, 5]
ANGLE_SERVO_PIN = 6
SERVO_FREQUENCY_HZ = 50

# === STEPPER PHYSIK ===

WHEEL_DIAMETER_MM = 67
TRACK_WIDTH_MM = 120
STEPPER_MICRO = 16
STEPPER_MIN_SPEED = 5
STEPPER_MAX_SPEED = 200
STEPPER_ACCELERATION = 2000
GUN_GEAR_RATIO = 5

# === POSITIONEN ===

POS_0 = 0
POS_90 = 90