# file: config.py

# === WIFI ===

SSID_AP = "MeinRoboter"
PASSWORD_AP = "Robo1234"

# === SERVO ===

CANNON_SERVO_PINS = [2, 3, 4, 5]
ANGLE_SERVO_PIN = 6
SERVO_FREQUENCY_HZ = 50

# === STEPPER PHYSIK ===

WHEEL_DIAMETER_MM = 67
TRACK_WIDTH_MM = 130

# Drive stepper parameters
DRIVE_STEPPER_MICRO = 16
DRIVE_STEPPER_MIN_SPEED = 5
DRIVE_STEPPER_MAX_SPEED = 300
DRIVE_STEPPER_ACCELERATION = 300

# Gun stepper parameters
GUN_STEPPER_MICRO = 16
GUN_STEPPER_MIN_SPEED = 5
GUN_STEPPER_MAX_SPEED = 100
GUN_STEPPER_ACCELERATION = 100


GUN_GEAR_RATIO = 5

# === POSITIONEN ===

POS_0 = 0
POS_90 = 90